services:
  # PostgreSQL - Metadata database for Uptrace (separate from main app)
  uptrace-postgres:
    image: postgres:16-alpine
    container_name: uptrace-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: uptrace
      POSTGRES_PASSWORD: uptrace
      POSTGRES_DB: uptrace
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uptrace -d uptrace"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - uptrace_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Different port to avoid conflict with main app postgres
    networks:
      - uptrace-network

  # ClickHouse - Telemetry data storage for Uptrace
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - uptrace_clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native interface
    networks:
      - uptrace-network

  # Uptrace - All-in-one observability platform
  uptrace:
    image: uptrace/uptrace:1.7.0
    container_name: uptrace
    restart: unless-stopped
    volumes:
      - ./uptrace.yml:/etc/uptrace/uptrace.yml:ro
    ports:
      - "14317:14317"  # OTLP gRPC receiver
      - "14318:14318"  # OTLP HTTP receiver  
      - "14319:14319"  # Uptrace UI
    environment:
      - UPTRACE_CONFIG_PATH=/etc/uptrace/uptrace.yml
    networks:
      - uptrace-network
    depends_on:
      uptrace-postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:14319/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # OpenTelemetry Collector - for advanced routing
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otelcol-contrib/otel-collector.yaml"]
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-contrib/otel-collector.yaml:ro
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter metrics
    depends_on:
      uptrace:
        condition: service_healthy
    networks:
      - uptrace-network

volumes:
  uptrace_postgres_data:
  uptrace_clickhouse_data:

networks:
  uptrace-network:
    name: uptrace-network
    driver: bridge