receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 256
    check_interval: 1s

exporters:
  # SigNoz exporter
  otlp/signoz:
    endpoint: "otel-collector-signoz:4317"  # gRPC endpoint to SigNoz OTel collector
    tls:
      insecure: true

  # Debug exporter for development
  debug:
    verbosity: detailed

  # Prometheus metrics exporter
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp/signoz, debug ]
    
    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp/signoz, prometheus ]
    
    logs:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp/signoz, debug ]

  extensions: [ ]