receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 256
    check_interval: 1s

exporters:
  # Uptrace exporter
  otlp/uptrace:
    endpoint: "http://uptrace:14317"
    tls:
      insecure: true
    headers:
      uptrace-dsn: "http://project1_secret_token@uptrace:14317/1"

  # Debug exporter for development
  debug:
    verbosity: detailed

  # Prometheus metrics exporter
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp/uptrace, debug ]
    
    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp/uptrace, prometheus ]
    
    logs:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp/uptrace, debug ]

  extensions: [ ]